task 1 ready
KirillTepechin/test-mediasoft pull request #1
Opened 2024-04-21 10:04 UTC by KirillTepechin

2024-04-21 19:15 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "task 1 ready". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 19:29 UTC, GUR-ok requested changes

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/aspect/ExecutionTimeAspect.java
> +        System.out.printf("Execution time of %s method from the %s = %d ms%n", methodName, className, endTime);
sout не используем в боевом закоммиченном коде. давай через логирование

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/aspect/ExecutionTimeAspect.java
> +            e.printStackTrace();
а этот catch не препятствует пробросу исключений наружу контроллера? Например у тебя метод getById бросает NotFoundException. Повесь над ним аннотацию замера времени. тебе в овтет null вернется, если поискать по несуществующему айди. и причем 200

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/aspect/TransactionAspect.java
> +        //startTime = System.currentTimeMillis();
зачем этот метод?

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/aspect/TransactionAspect.java
> +        System.out.printf("Transaction time: %d ms%n", System.currentTimeMillis() - startTime);
sout не юзаем. логировать

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/configuration/ScheduleConfiguration.java
> +@EnableScheduling
вместо этого класса давай просто повесить над самым главном классом приложения

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/scheduler/OptimizedProductPriceScheduler.java
> +            fileUtil.close();
Connection -> creates and automatically closes -> Statement
Statement -> creates and automatically closes -> ResultSet	

Можно клозить только connection, поместив его в блок try-with-resource

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/scheduler/OptimizedProductPriceScheduler.java
> +            String query = "WITH updated AS (UPDATE Product SET price = price + (price * ? / 100) RETURNING *)\n" +
Не нагружаем cpu бд вычислениями. бд плохо масштабируется горизонтально. обязательно нужно новую цену считать на стороне сервиса.

2024-04-21 19:29 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/util/FileUtil.java
> +            writer.close();
если writer поместить в try-with-resource, то этот метод не нужен. выглядит как лишний утильный класс. хотя бы может быть файл создавал если отсутствует. или имя файла принимал. я бы убрал вообще, поместил в код шедулера пару строк и все.

2024-04-22 05:03 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/scheduler/OptimizedProductPriceScheduler.java
> +            String query = "WITH updated AS (UPDATE Product SET price = price + (price * ? / 100) RETURNING *)\n" +
про вычисления на стороне бд обсудили в чате. оставляем. только зачем тут with и селект, если можно просто 
UPDATE Product SET price = price + (price * ? / 100) RETURNING * ?

2024-04-22 14:33 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/scheduler/OptimizedProductPriceScheduler.java
> +            String query = "WITH updated AS (UPDATE Product SET price = price + (price * ? / 100) RETURNING *)\n" +
В таком случае в запросе нельзя будет указать for update

2024-04-23 20:36 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/util/FileUtil.java
> +            writer.close();
Все замечания исправлены

2024-04-25 13:47 UTC, GUR-ok approved these changes

2024-04-25 17:46 UTC, merged