Task2: add multi-criteria search
KirillTepechin/test-mediasoft pull request #2
Opened 2024-04-25 17:39 UTC by KirillTepechin

2024-04-27 07:20 UTC, GUR-ok commented
конфликты

2024-04-27 07:33 UTC, GUR-ok requested changes

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/controller/ProductController.java
> +
лишняя пустая строка

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/controller/ProductController.java
>  import org.springframework.web.bind.annotation.*;
импорты

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/search/SearchCriteria.java
> +    class StringSearchCriteria implements SearchCriteria<String> {
вынеси в отдельные файлы пожалуйста

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/search/criteria/SpecificationBuilder.java
> +            new AbstractMap.SimpleEntry<>(OperationType.LIKE, new LikePredicateBuilder()),
почему мапу создал так странно? через Map.of не получится?

2024-04-27 07:33 UTC, GUR-ok commented on src/test/java/com/mediasoft/warehouse/ProductSearchDataJpaTest.java
> +import static org.junit.jupiter.api.Assertions.*;
импорты

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/search/criteria/EqPredicateBuilder.java
> +package com.mediasoft.warehouse.service.search.criteria;
это пакет для предикат билдеров

2024-04-27 07:33 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/search/criteria/PredicateBuilder.java
> +        if(IntegerSearchCriteria.class.equals(searchCriteria.getClass())){
после if пробел. нажми плз тут ctrl+alt+L
Чтобы не использовать рефлексию, можно было стратегии формирования предкиатов положить в searchCriteria. покажу на занятии

2024-04-28 08:34 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/service/search/criteria/PredicateBuilder.java
> +        if(IntegerSearchCriteria.class.equals(searchCriteria.getClass())){
Замечания исправлены,  конфликты разрешены

2024-05-01 10:37 UTC, GUR-ok approved these changes

2024-05-01 10:38 UTC, GUR-ok commented
можно вмержить со сквошем

2024-05-01 10:52 UTC, merged