Task3: add conversion of currency rates
KirillTepechin/test-mediasoft pull request #5
Opened 2024-05-01 13:15 UTC by KirillTepechin

2024-05-04 11:54 UTC, GUR-ok requested changes

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/CurrencyFilter.java
> +    @Autowired
не надо так пожалуйста

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/CurrencyFilter.java
> +            currencyProvider.setCurrentCurrency(Currency.valueOf(currencyString));
Давай попробуем через опшнл
```
        Optional.ofNullable(currencyString )
           .map(Currency::valueOf)
           .ifPresent(currencyProvider::setCurrentCurrency);
```

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientImpl.java
> +    @Value("${currency-service.host}")
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientImpl.java
> +    private final WebClient webClient = WebClient.create();
webClient создать бином через файл конфигурации. там сразу зашить хост

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientImpl.java
> +                .uri(host + endpoint)
тут хост не передавать. будет зашит в бин вебклиента в baseurl

2024-05-04 11:54 UTC, GUR-ok commented on src/main/resources/application.yaml
> +currency-service:
```
rest:
   currency-service:
      host:
      methods: ...
      mock:
         enabled: true
```

2024-05-04 11:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientMock.java
> +@ConditionalOnProperty("currency-service.mock")
задать дефолтное значение на случай отсутствия конфига currency-service.mock

2024-05-04 15:32 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientMock.java
> +@ConditionalOnProperty("currency-service.mock")
Так он же по дефолту false, при отсутствии конфига создается другой сервис

2024-05-04 16:47 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientMock.java
> +@ConditionalOnProperty("currency-service.mock")
да, похоже на правду

2024-05-04 17:58 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/currency/service/CurrencyServiceClientMock.java
> +@ConditionalOnProperty("currency-service.mock")
Исправил все замечания

2024-05-12 06:35 UTC, GUR-ok approved these changes
можно мержить со сквошем

2024-05-12 17:25 UTC, merged