Task4: add products ordering
KirillTepechin/test-mediasoft pull request #6
Opened 2024-05-09 17:03 UTC by KirillTepechin

![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/fb02d567-32a2-499a-9de8-3dd0606ce812)

2024-05-12 06:54 UTC, GUR-ok requested changes

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +            Product productFromDb = productsFromDb.stream()
стрим в стриме дает квадратичную алгоритмическую сложность. Взамен productsFromDb.stream() обращайся к хэшмапе из айди товаров и найденных товаров
```
        final Map<UUID, ProductEntity> productMap = productList.stream()
                .collect(Collectors.toMap(ProductEntity::getId, Function.identity()));
```

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +        Order orderFromDb = orderRepository.findById(orderUuid)
у тебя здесь селектится ордер а потом селектится orderProductsFromDb. не хотим добавить связь oneToMany в ордер, чтобы тут одним запросом извлечь?

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +        return order.getUuid();
покажи плз скрин запросов хибернейт после выполнения этого метода

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +        List<GetOrderProductDto> orderProducts = orderRepository.findOrderProductsByOrderUuid(orderUuid);
Мы получили ордер, чтобы получить кастомера. а может проекции срfзу получим, передав в запрос репозитория еще и кастомера? например так у меня
```
    @Query("""
                select new com.crudshop.demo.entity.projection.ProductProjection (
                    op.orderedProductKey.productId,
                    pe.description,
                    op.quantity,
                    op.price
                  )
                from OrderedProduct op
                  join ProductEntity pe on pe.id = op.orderedProductKey.productId
                  join OrderEntity oe on oe.id = op.orderedProductKey.orderId
                where op.orderedProductKey.orderId = :orderId
                and oe.customer.id = :customerId
            """)
    List<ProductProjection> getProjectionsByOrderIdAndCustomerId
            (UUID orderId, UUID customerId);
```

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +            Product productFromDb = productsFromDb.stream()
здесь тоже цикл в цикле нужно заменить на цикл, обращающися к хэшмапе

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +            orderProductsFromDb.stream()
здесь еще один стрим нужно ликвидировать

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +        List<Product> products = productRepository.findAllById(orderProducts.stream()
когда будет связь oneToMany в order. то все можно будет поулчить одним запросом, а не тремя.

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/model/Order.java
> +import jakarta.persistence.*;
импорты

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/model/Customer.java
> +import jakarta.persistence.*;
импорты

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +                    .filter(p -> p.getUuid().equals(product.getUuid()))
причем sumAndRemoveDuplicates внутри еще содержит стрим. это все нужно оптимизировать. Всего должен быть 1 foreach, который проходится по товарам из пришедшего запроса и создает новый OrderProduct или апдейтит имеющийся

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/model/OrderProductId.java
> +    private UUID orderUuid;
название не принято привязывать к типу. давай orderId и productId

2024-05-12 06:54 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/repository/OrderProductRepository.java
> +    @Query("SELECT op FROM OrderProduct op WHERE op.id.orderUuid = :orderUuid")
кажется квери можно убрать, назвав метод findAllByOrderProductIdOrderId (orderId только переименуй)

2024-05-12 17:37 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +        return order.getUuid();
![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/e826bb23-000d-4753-a7c4-3748055afb26)

2024-05-13 14:26 UTC, KirillTepechin commented
Исправил часть замечаний, проблему n+1 никак не решал, однако при апдейте лишних запросов не появляется(скрин), аналогично с остальными методами, может я чего то не понимаю?
![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/50bf8480-0cd0-442a-ac45-37a5c022252c)

2024-05-13 14:28 UTC, KirillTepechin commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +                    .filter(p -> p.getUuid().equals(product.getUuid()))
Не совсем понимаю, как тогда сделать более оптимизированно удаление дубликатов и суммирование их quantity?

2024-05-20 09:40 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/OrderService.java
> +                    .filter(p -> p.getUuid().equals(product.getUuid()))
показал на лекции, там используются две вспомогательные мапы

2024-05-20 09:42 UTC, GUR-ok commented
Напиши плз в личку, когда поправишь до конца.

2024-05-20 16:23 UTC, KirillTepechin commented
Исправил замечания. Теперь при апдейте 2 селекта как в лекции. Получается что хибер все-таки не вызывает n+1, тк иначе он бы делал селект на каждый order_product
![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/8363ff17-93a8-4b60-9b2b-222b8929cec4)

2024-05-21 04:55 UTC, GUR-ok approved these changes
Ок давай подмержим со сквошем

2024-05-21 07:39 UTC, merged