Task 6: add kafka event handlers
KirillTepechin/test-mediasoft pull request #8
Opened 2024-05-30 16:32 UTC by KirillTepechin

Не получилось подключиться через ui к кафке в кластере.
Как будто получается достучаться, но в итоге timeout.
![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/dee5e78f-e695-483b-bfa2-e8ccc14c2cb2)
![image](https://github.com/KirillTepechin/test-mediasoft/assets/90400949/5f585098-9cab-445c-ad1d-e386e2cde00a)

2024-06-01 08:36 UTC, GUR-ok requested changes
Зря сделал от ветки task5. Этому задание не нужны были изменения из прошлого задания. Сделай ребейз на девелоп. Пока смотреть не смогу иначе. 58 файлов измененных (посмотри сам в шапке мр тут).

2024-06-01 08:40 UTC, GUR-ok commented
> Не получилось подключиться через ui к кафке в кластере. Как будто получается достучаться, но в итоге timeout. ![image](https://private-user-images.githubusercontent.com/90400949/335302276-dee5e78f-e695-483b-bfa2-e8ccc14c2cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzEzMDQsIm5iZiI6MTcxNzIzMTAwNCwicGF0aCI6Ii85MDQwMDk0OS8zMzUzMDIyNzYtZGVlNWU3OGYtZTY5NS00ODNiLWJmYTItZThjY2MxNGMyY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA4MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNjQ1OWVkY2VhYjBkMTYzYWY0MGFiODFmOWVmN2I5YTdhYmMwYTBkNmZlYTliYTY4ZjNkY2E5YjYxN2UzNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9PB5Zv02Pv_unyzHMnwRafsNaBJNaw6UnAE0m86VCY) ![image](https://private-user-images.githubusercontent.com/90400949/335302656-5f585098-9cab-445c-ad1d-e386e2cde00a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzEzMDQsIm5iZiI6MTcxNzIzMTAwNCwicGF0aCI6Ii85MDQwMDk0OS8zMzUzMDI2NTYtNWY1ODUwOTgtOWNhYi00NDVjLWFkMWQtZTM4NmUyY2RlMDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA4MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTFkMGE4MzhjZmM4OWE5OTg4M2Y2M2Y2MjllZWIxMDQ0MWI1YjFiY2Q5YjQ2M2QyN2VjYWMzYWQ5OTY5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBBxYvtPP456nPakrDdXbWoqMydqpiw9vuB7t26ZLjo)

чтобы подключиться через ui к кафке в кластеру, нужно использовать ui kafka manager, который внутри кластера. или делать port-forward брокеров из кластера наружу, тк сеть миникуба изолирована от локалхоста.

2024-06-01 11:33 UTC, KirillTepechin commented
Запушил

2024-06-08 09:23 UTC, GUR-ok approved these changes
Вроде основные моменты ок, давай мержить со сквошем.

2024-06-08 11:29 UTC, merged