Task7: add product images functionality
KirillTepechin/test-mediasoft pull request #9
Opened 2024-06-05 13:01 UTC by KirillTepechin

2024-06-05 13:05 UTC, KirillTepechin commented
PR проекта со стартером:
[https://github.com/KirillTepechin/exception-handler-starter/pull/1](url)

2024-06-15 09:06 UTC, GUR-ok requested changes

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +        PutObjectRequest putObjectRequest = getPutObjectRequest(file, bucketName, key);
давай везде final сделаем, где объявляем локальные переменные. Например final PutObjectRequest putObjectRequest, final ObjectMetadata metadata. Во всех методах этого класса

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +    private PutObjectRequest getPutObjectRequest(MultipartFile file, String bucketName, String key) {
лучше называть не getPutObjectRequest, а buildPutObjectRequest

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/controller/ProductController.java
> +    @PatchMapping(value = "/{uuid}/upload", consumes = MULTIPART_FORM_DATA)
Давай все таки POST

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/controller/ProductController.java
> +    public byte[] downloadProductImages(@PathVariable UUID uuid){
Давай byte[] заменим на StreamingResponseBody. Так лучше по памяти по использованию тредов. OutputStream придется передавать в сервисный метод и в него писать zip архив.

Псевдокодный пример как передать outputStream в сервис
```
    @GetMapping("/foo")
    public StreamingResponseBody downloadZip() {
        StreamingResponseBody stream = out -> {
            вызовСервисаДляЗагрузкиАрхива(out);
        };
        
        return stream;
    }
```

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +    public byte[] downloadFilesFromBucket(String bucketName, List<String> keys) {
Тут в аргументах придется принимать outputStream, в который мы будем писать зипархив. outputStream придет из контроллера. Метод byte[] не возвращает. можно void

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +    private final String ARCHIVE_PATH = "src/main/resources/archive.zip";
ARCHIVE_PATH убираем. мы ничего не сохраняем

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +                    int lastIndex = decodeFilename.lastIndexOf(".");
Супер, что учел дублирование имен. Но эту логику нужно в приватный метод вынести. Тк ухудшает читаемость и воможно потребуется переиспользовать в этом классе в будущем
стрим в трай с ресурсами, чтобы не клозить вручную

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +        try(FileOutputStream fos = new FileOutputStream(ARCHIVE_PATH);
FileOutputStream убираем

2024-06-15 09:06 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/service/S3StorageService.java
> +            ZipOutputStream zipOut = new ZipOutputStream(fos)){
ZipOutputStream нужно создать, передав внутрь конструктора outPutstream, который придет в аргументах

2024-06-15 09:11 UTC, GUR-ok commented on src/main/java/com/mediasoft/warehouse/controller/ProductController.java
> +    public byte[] downloadProductImages(@PathVariable UUID uuid){
будет на самом деле ```ResponseEntity<StreamingResponseBody>```. нужно еще хедеры не забыть положить в ResponseEntity c content-disposition

2025-10-14 22:43 UTC, merged